---
kind: pipeline
name: default

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: build
    image: plugins/hugo
    settings:
      hugo_version: 0.78.2
      validate: true
      output: public_html/
  # - name: deploy
  #   image: cschlosser/drone-ftps
  #   settings:
  #     hostname: ftp.fastmail.com
  #     clean_dir: false
  #     chmod: false
  #     verify: false
  #     secure: false
  #     dest_dir: /neil.grogan.org/files/neilgrogan.com
  #     src_dir: /public_html
  #   environment:
  #     FTP_USERNAME:
  #       from_secret: FTP_USER
  #     FTP_PASSWORD:
  #       from_secret: FTP_PASS
  - name: Deploy via rsync
    image: drillster/drone-rsync
    settings:
      hosts: [ "192.168.1.3" ]
      source: ./public_html/
      target: ~/Cloud/FMDav/neilgrogan.com
      recursive: true
      delete: true
      key:
        from_secret: RSYNC_KEY
      user:
        from_secret: RSYNC_USER

  - name: Email Notification
    image: drillster/drone-email
    environment:
      EMAIL_HOST:
        from_secret: EMAIL_SMTP_HOST
      EMAIL_USERNAME:
        from_secret: EMAIL_USER
      EMAIL_PASSWORD:
        from_secret: EMAIL_PASS
    settings:
      from:
        from_secret: EMAIL_FROM
      branch:
        - develop
        - master
    when:
      status: [ changed, failure ]
