ignoreFiles = [ "node_modules" ]
relativeURLs = true
languageCode = "en-us"
title = "Neil Grogan"
theme = "PaperMod"
googleAnalytics = "G-EC18YZQL99"
copyright = "© 2004-present [Neil Grogan](/)"

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  static = "/img/"

[author]
  name = "Neil Grogan"

[params]
  env = "production"
  description = "Neil Grogan"
  author = "Neil Grogan"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

  [params.homeInfoParams]
    Title = "Neil Grogan"
    Content = "Personal blog and notes."

  [params.social]
    twitter = "dueyfinster"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/dueyfinster"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dueyfinster"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/neil-grogan"

  [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.ie/@dueyfinster"

  [[menu.main]]
     name = "About"
     weight = 1
     identifier = "about"
     url = "/about"

  [[menu.main]]
    identifier = "uses"
    name = "Uses"
    url = "/uses"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4

  [[menu.main]]
	  name = "Archives"
	  identifier = "archives"
	  url = "/archives/"
	  weight = 5

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 7

[outputs]
  home = ["HTML", "RSS", "JSON"]

[security]
  allowContent = ['^text/(html|markdown|org)$', '^application/pdf$']


[markup.goldmark.renderer]
  unsafe = true
