ignoreFiles = [ "node_modules" ]
relativeURLs = true
languageCode = "en-us"
title = "Neil Grogan"
theme="noteworthy"
googleAnalytics = ""

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  static = "/img/"

[author]
  name = "Neil Grogan"

[Social]
  twitter = "dueyfinster"
  github = "dueyfinster"
  linkedin = "neil-grogan"

[params]

  [[menu.main]]
     name = "About"
     weight = 1
     identifier = "about"
     url = "/about"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 2

  [[menu.main]]
    name = "Presentations"
    weight = 3
  	identifier = "presentations"
    url = "/presentations/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/posts/"
    weight = 5

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 5


[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "index"


[markup.goldmark.renderer]
  unsafe = true
