ignoreFiles = [ "node_modules" ]
relativeURLs = true
languageCode = "en-us"
title = "Neil Grogan"
theme="econtra"
googleAnalytics = ""

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  static = "/img/"

[author]
  name = "Neil Grogan"

[Social]
  twitter = "dueyfinster"
  github = "dueyfinster"
  linkedin = "neil-grogan"

[params]
  enableLunrSearch = true


  [[menu.main]]
     name = "About"
     weight = 1
     identifier = "about"
     url = "/about"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4

  [[menu.main]]
	  name = "Archives"
	  identifier = "archives"
	  url = "/archives/"
	  weight = 5

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 6

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "index"

  [outputFormats.SearchIndex]
  mediatype = "application/json"
  baseName = "search"

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]


[markup.goldmark.renderer]
  unsafe = true