# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Econtra"
license = "MIT"
licenselink = "https://github.com/dueyfinster/neiulgrogam.com/blob/master/LICENSE"
description = ""
homepage = "http://www.neilgrogan.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = "noteworthy"
  homepage = "https://github.com/kimcc/hugo-theme-noteworthy"
  repo = ""
