name: Build with Emacs and publish to Github pages
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: build
      uses: docker://iquiw/alpine-emacs
      if: github.event.deleted == false
      with:
        args: emacs --batch --no-init-file --load publish.el --funcall toggle-debug-on-error --funcall org-publish-all
    - name: deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
